### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedReader.close()' on a null object reference

### ISSUE THREAD

**Issue by matthewtole** [matthewtole/linkfix#2]
``` bash
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedReader.close()' on a null object reference
at com.bugsense.trace.Utils.manageUid(Unknown Source)
at com.bugsense.trace.BugSenseHandler$1.run(Unknown Source)
at java.lang.Thread.run(Thread.java:811)

```

**Comment by raoudhaa** [comment]
i have the same error
